import type { Metadata } from "next";
import Providers from '@/components/Providers';
import "./globals.css";
import { PostProvider } from "@/context/PostContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <PostProvider>{children}</PostProvider>
        </Providers>
      </body>
    </html>
  );
}
